path_bordeaux = "./data/InstancesV1/InstanceBordeauxV1.xlsx"
path_finland = "./data/InstancesV1/InstanceFinlandV1.xlsx"
path_guinea_golf = "./data/InstancesV1/InstanceGuineaGolfV1.xlsx"
path_italy = "./data/InstancesV1/InstanceItalyV1.xlsx"
path_poland = "./data/InstancesV1/InstancePolandV1.xlsx"

path_bordeaux_v2 = "./data/InstancesV2/InstanceBordeauxV2.xlsx"
path_australia_v2 = "./data/InstancesV2/InstanceAustraliaV2.xlsx"
path_austria_v2 = "./data/InstancesV2/InstanceAustraliaV2.xlsx"
path_poland_v2 = "./data/InstancesV2/InstancePolandV2.xlsx"
path_spain_v2 = "./data/InstancesV2/InstanceSpainV2.xlsx"
